# Generated by Django 5.1.7 on 2025-04-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0002_shoppingitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingitem",
            name="is_urgent",
            field=models.BooleanField(default=False),
        ),
    ]
