# Generated by Django 5.1.7 on 2025-04-05 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("households", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("due_date", models.DateField()),
                ("is_done", models.BooleanField(default=False)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Repeat every X days if recurring",
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="households.household",
                    ),
                ),
            ],
        ),
    ]
