# Generated by Django 5.1.7 on 2025-04-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0002_alter_chore_assigned_to_alter_chore_household"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
