# Generated by Django 5.2 on 2025-05-09 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_chore_completed_at'),
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='finished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_chores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chore',
            name='household',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='households.household'),
            preserve_default=False,
        ),
    ]
